# Generated by Django 6.0 on 2025-12-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('room_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_request', 'No Request')], default='no_request', max_length=20)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('office', 'Office'), ('stairs', 'Stairs'), ('hallway', 'Hallway'), ('cr', 'Restroom'), ('lab', 'Laboratory'), ('lobby', 'Lobby'), ('other', 'Other')], default='classroom', max_length=20)),
                ('request_count', models.IntegerField(default=0)),
                ('special', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
                'indexes': [models.Index(fields=['building', 'floor'], name='api_room_buildin_1110a3_idx'), models.Index(fields=['status'], name='api_room_status_6704bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requester_name', models.CharField(blank=True, max_length=100)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
