# Generated by Django 6.0 on 2025-12-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_building_rename_name_room_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='api_room_buildin_2875eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='api_room_status_6704bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='api_room_room_ty_732361_idx',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='created_by',
        ),
        migrations.AddField(
            model_name='room',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='special',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.room'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cr_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
    ]
